// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eptxocvafwoirxnljtwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwdHhvY3ZhZndvaXJ4bmxqdHdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1OTkzNjgsImV4cCI6MjA4OTE3NTM2OH0.SHUsLTNq4lW0ghkqlGUG3euZmV_zqqnhaOL6rRqROzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});